### ISSUE TITLE
ruptime down since

### ISSUE THREAD

**Issue by alexmyczko** [alexmyczko/ruptime#1]
```
dpkg -l |grep ^h |wc -l
apt-show-versions |grep -v uptodate$ | wc -l
```

maybe also show if a dist-upgrade is running, adding a state to `ruptime`, currently only showing UP or DOWN
OSUP+ETA?

then there could also be .zZ for sleep state, later when power management features are implemented/added

https://pip.pypa.io/en/stable/cli/pip_list/

**Comment by alexmyczko** [comment]
down since?
TIME_STYLE=+%s ls -l

**Comment by crpb** [comment]
`apt-show-versions` has the hickups with advanced sources (multiple releases).

`upgradable=$(apt list '?upgradable' 2>/dev/null |grep -c upgradable)`

**Comment by alexmyczko** [comment]
as long as there are so many different distros of linux i gave up on this idea. down since will get implemented only

**Comment by alexmyczko** [comment]
find .  -name "*.ruptime" -mmin +10 -exec cat {} \; |sed "s,up.*,down,g" |while read a b; do echo $a $b $(TIME_STYLE=+%s ls -l ${a}.ruptime|awk -vNOW=$(date +%s) '{print ((NOW-$(6))/60) }'); done
